In [1]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
df = pd.read_csv('data/breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
print(df.shape)
print(type(df))
print(df.info())
print(df.isnull().sum())

(569, 32)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB
None
id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [13]:
df = df.drop(columns=['id'])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [19]:
y = df['diagnosis'].map({'M': 1, 'B': 0})
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['diagnosis']), y, test_size=0.2, random_state=42)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print()
print(y.value_counts())

(455, 30) (455,)
(114, 30) (114,)

diagnosis
0    357
1    212
Name: count, dtype: int64

In [18]:
b_count = 0
m_count = 0
for i in y:
    if i == 0:
        b_count += 1
    else:
        m_count += 1

print(f'Benign count: {b_count}')
print(f'Malignant count: {m_count}')

Benign count: 357
Malignant count: 212

In [22]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)
print(X_test_scaled)

[[-1.44075296 -0.43531947 -1.36208497 ...  0.9320124   2.09724217
   1.88645014]
 [ 1.97409619  1.73302577  2.09167167 ...  2.6989469   1.89116053
   2.49783848]
 [-1.39998202 -1.24962228 -1.34520926 ... -0.97023893  0.59760192
   0.0578942 ]
 ...
 [ 0.04880192 -0.55500086 -0.06512547 ... -1.23903365 -0.70863864
  -1.27145475]
 [-0.03896885  0.10207345 -0.03137406 ...  1.05001236  0.43432185
   1.21336207]
 [-0.54860557  0.31327591 -0.60350155 ... -0.61102866 -0.3345212
  -0.84628745]]
[[-0.46649743 -0.13728933 -0.44421138 ... -0.19435087  0.17275669
   0.20372995]
 [ 1.36536344  0.49866473  1.30551088 ...  0.99177862 -0.561211
  -1.00838949]
 [ 0.38006578  0.06921974  0.40410139 ...  0.57035018 -0.10783139
  -0.20629287]
 ...
 [-0.73547237 -0.99852603 -0.74138839 ... -0.27741059 -0.3820785
  -0.32408328]
 [ 0.02898271  2.0334026   0.0274851  ... -0.49027026 -1.60905688
  -0.33137507]
 [ 1.87216885  2.80077153  1.80354992 ...  0.7925579  -0.05868885
  -0.09467243]]

In [23]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)
print(y_train_encoded)
print(y_test_encoded)

[0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0
 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 0 1 0 1
 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0
 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 0 1 1
 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1
 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 1 0 0 1 1 1 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 1
 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0
 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0
 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1
 0 1 1 0 1 0 0 0 0 1 0]
[0 1 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 1
 0 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 0 1
 0 0 1]

**numpy arrays to pytorch tensors**

In [28]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)
print(X_train_tensor)
print(X_test_tensor)
print(y_train_tensor)
print(y_test_tensor)

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)
tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]],
       dtype=torch.float64)
tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])
tensor([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [ ]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.rand(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        return torch.sigmoid(X @ self.weights + self.bias)
    
    def loss_function(self, y_pred, y_true):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss = -torch.mean(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
        return loss

In [48]:
learning_rate = 0.01
epochs = 1000

In [49]:
model = MySimpleNN(X_train_tensor)
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)

    # Compute loss
    loss = model.loss_function(y_pred, y_train_tensor)
    # print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

    # Backward pass
    loss.backward()

    # Update weights and bias
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")

Epoch 1/1000, Loss: 3.5338794254849764
Epoch 2/1000, Loss: 3.522095426358086
Epoch 3/1000, Loss: 3.510324275906463
Epoch 4/1000, Loss: 3.4985660768669185
Epoch 5/1000, Loss: 3.486820933529303
Epoch 6/1000, Loss: 3.47508895179606
Epoch 7/1000, Loss: 3.4633046237625904
Epoch 8/1000, Loss: 3.4514305558078817
Epoch 9/1000, Loss: 3.4395543229479166
Epoch 10/1000, Loss: 3.427415691053008
Epoch 11/1000, Loss: 3.4151521509925664
Epoch 12/1000, Loss: 3.4028870375895535
Epoch 13/1000, Loss: 3.3904749007659345
Epoch 14/1000, Loss: 3.378077959019689
Epoch 15/1000, Loss: 3.365696350096357
Epoch 16/1000, Loss: 3.353330214276197
Epoch 17/1000, Loss: 3.3409666976465484
Epoch 18/1000, Loss: 3.3284253716666075
Epoch 19/1000, Loss: 3.315900373002983
Epoch 20/1000, Loss: 3.303391857440225
Epoch 21/1000, Loss: 3.290899983736175
Epoch 22/1000, Loss: 3.2784021835138835
Epoch 23/1000, Loss: 3.2656796840674853
Epoch 24/1000, Loss: 3.252716149797837
Epoch 25/1000, Loss: 3.2394607075081088
Epoch 26/1000, Loss: 3.2260954164364213
Epoch 27/1000, Loss: 3.212749896274021
Epoch 28/1000, Loss: 3.199424355698638
Epoch 29/1000, Loss: 3.1860519570575696
Epoch 30/1000, Loss: 3.172548671864967
Epoch 31/1000, Loss: 3.159066297634846
Epoch 32/1000, Loss: 3.145605065609293
Epoch 33/1000, Loss: 3.132165211676417
Epoch 34/1000, Loss: 3.1187469764272864
Epoch 35/1000, Loss: 3.1053506052107784
Epoch 36/1000, Loss: 3.0919763481858835
Epoch 37/1000, Loss: 3.078624460375341
Epoch 38/1000, Loss: 3.065295201707785
Epoch 39/1000, Loss: 3.0519888370581127
Epoch 40/1000, Loss: 3.038705636295302
Epoch 41/1000, Loss: 3.0254458743093635
Epoch 42/1000, Loss: 3.01220983105146
Epoch 43/1000, Loss: 2.9989977915577737
Epoch 44/1000, Loss: 2.9858100459707027
Epoch 45/1000, Loss: 2.972646889572448
Epoch 46/1000, Loss: 2.959508622792546
Epoch 47/1000, Loss: 2.9463955512283704
Epoch 48/1000, Loss: 2.9332851805970535
Epoch 49/1000, Loss: 2.920004284768154
Epoch 50/1000, Loss: 2.906749967688054
Epoch 51/1000, Loss: 2.8934089737708693
Epoch 52/1000, Loss: 2.879926015352566
Epoch 53/1000, Loss: 2.8664713709504532
Epoch 54/1000, Loss: 2.852948729691052
Epoch 55/1000, Loss: 2.8392832663443133
Epoch 56/1000, Loss: 2.825524245202983
Epoch 57/1000, Loss: 2.811601954410454
Epoch 58/1000, Loss: 2.7976963681681597
Epoch 59/1000, Loss: 2.7835418465012634
Epoch 60/1000, Loss: 2.769421085677036
Epoch 61/1000, Loss: 2.7553345430671636
Epoch 62/1000, Loss: 2.741271017479166
Epoch 63/1000, Loss: 2.7270287038541707
Epoch 64/1000, Loss: 2.712808167213942
Epoch 65/1000, Loss: 2.698450372323684
Epoch 66/1000, Loss: 2.6841297145166454
Epoch 67/1000, Loss: 2.6698467097398004
Epoch 68/1000, Loss: 2.655601880598341
Epoch 69/1000, Loss: 2.6413957563207644
Epoch 70/1000, Loss: 2.6272288726703374
Epoch 71/1000, Loss: 2.613100981434374
Epoch 72/1000, Loss: 2.598720754817342
Epoch 73/1000, Loss: 2.5843824167172764
Epoch 74/1000, Loss: 2.570086550158384
Epoch 75/1000, Loss: 2.5558337447187136
Epoch 76/1000, Loss: 2.541624596445974
Epoch 77/1000, Loss: 2.527459707778784
Epoch 78/1000, Loss: 2.5133396874588265
Epoch 79/1000, Loss: 2.4992651504468695
Epoch 80/1000, Loss: 2.4852367178237875
Epoch 81/1000, Loss: 2.4712550167013685
Epoch 82/1000, Loss: 2.4573206801249063
Epoch 83/1000, Loss: 2.4434343469553665
Epoch 84/1000, Loss: 2.429596661784697
Epoch 85/1000, Loss: 2.415808274802478
Epoch 86/1000, Loss: 2.402069841693724
Epoch 87/1000, Loss: 2.388382023501261
Epoch 88/1000, Loss: 2.3747454865084467
Epoch 89/1000, Loss: 2.361160902093056
Epoch 90/1000, Loss: 2.347628946587936
Epoch 91/1000, Loss: 2.334150301122999
Epoch 92/1000, Loss: 2.320725651469544
Epoch 93/1000, Loss: 2.3072779062592903
Epoch 94/1000, Loss: 2.293658120820893
Epoch 95/1000, Loss: 2.2800961002131097
Epoch 96/1000, Loss: 2.2665925797459985
Epoch 97/1000, Loss: 2.2531482987039677
Epoch 98/1000, Loss: 2.239764000101764
Epoch 99/1000, Loss: 2.2264404304169934
Epoch 100/1000, Loss: 2.2131451397877253
Epoch 101/1000, Loss: 2.1996522556728726
Epoch 102/1000, Loss: 2.186223722451076
Epoch 103/1000, Loss: 2.1728603274741087
Epoch 104/1000, Loss: 2.159562860252607
Epoch 105/1000, Loss: 2.1463321120774137
Epoch 106/1000, Loss: 2.1330319434787217
Epoch 107/1000, Loss: 2.1196395414423654
Epoch 108/1000, Loss: 2.1063175471744353
Epoch 109/1000, Loss: 2.092985657533449
Epoch 110/1000, Loss: 2.079541357478184
Epoch 111/1000, Loss: 2.0661708786613353
Epoch 112/1000, Loss: 2.052875070908156
Epoch 113/1000, Loss: 2.039654782523885
Epoch 114/1000, Loss: 2.026510859672695
Epoch 115/1000, Loss: 2.013342519227214
Epoch 116/1000, Loss: 2.000014413660091
Epoch 117/1000, Loss: 1.9864281039611735
Epoch 118/1000, Loss: 1.9728260221553722
Epoch 119/1000, Loss: 1.9591042735466642
Epoch 120/1000, Loss: 1.9454696060752155
Epoch 121/1000, Loss: 1.9319229542902134
Epoch 122/1000, Loss: 1.91846524535027
Epoch 123/1000, Loss: 1.9050973981479011
Epoch 124/1000, Loss: 1.8918203224537458
Epoch 125/1000, Loss: 1.8784319493170663
Epoch 126/1000, Loss: 1.8649149855328526
Epoch 127/1000, Loss: 1.8514956192686158
Epoch 128/1000, Loss: 1.8381747804925581
Epoch 129/1000, Loss: 1.824953384894466
Epoch 130/1000, Loss: 1.8118323329410124
Epoch 131/1000, Loss: 1.7988125089338887
Epoch 132/1000, Loss: 1.7858947800943292
Epoch 133/1000, Loss: 1.7730799956436858
Epoch 134/1000, Loss: 1.7603689859142475
Epoch 135/1000, Loss: 1.7476220330848946
Epoch 136/1000, Loss: 1.7343934185588803
Epoch 137/1000, Loss: 1.7212758416214886
Epoch 138/1000, Loss: 1.7082701491961154
Epoch 139/1000, Loss: 1.69537716441942
Epoch 140/1000, Loss: 1.682597685746783
Epoch 141/1000, Loss: 1.6699324860577673
Epoch 142/1000, Loss: 1.6573823118064124
Epoch 143/1000, Loss: 1.6449478821688925
Epoch 144/1000, Loss: 1.6326298882174406
Epoch 145/1000, Loss: 1.6204289921103936
Epoch 146/1000, Loss: 1.608345826303346
Epoch 147/1000, Loss: 1.5963809927827681
Epoch 148/1000, Loss: 1.5845350623086536
Epoch 149/1000, Loss: 1.5728085736836235
Epoch 150/1000, Loss: 1.5612020330431418
Epoch 151/1000, Loss: 1.5497159131628389
Epoch 152/1000, Loss: 1.5383506527927544
Epoch 153/1000, Loss: 1.527106656012574
Epoch 154/1000, Loss: 1.515984291614068
Epoch 155/1000, Loss: 1.5049838925091994
Epoch 156/1000, Loss: 1.4941057551697265
Epoch 157/1000, Loss: 1.4833501390943364
Epoch 158/1000, Loss: 1.4727172663120753
Epoch 159/1000, Loss: 1.4622073209198796
Epoch 160/1000, Loss: 1.4518204486549409
Epoch 161/1000, Loss: 1.441556756508024
Epoch 162/1000, Loss: 1.4314163123777321
Epoch 163/1000, Loss: 1.4213991447650853
Epoch 164/1000, Loss: 1.411505242514228
Epoch 165/1000, Loss: 1.4017345545962274
Epoch 166/1000, Loss: 1.3920869899410757
Epoch 167/1000, Loss: 1.3825624173154079
Epoch 168/1000, Loss: 1.3731606652496022
Epoch 169/1000, Loss: 1.3638815220118103
Epoch 170/1000, Loss: 1.3547247356320733
Epoch 171/1000, Loss: 1.3456900139743375
Epoch 172/1000, Loss: 1.336777024857469
Epoch 173/1000, Loss: 1.327985396224537
Epoch 174/1000, Loss: 1.3193147163595969
Epoch 175/1000, Loss: 1.3107645341523564
Epoch 176/1000, Loss: 1.30233435940875
Epoch 177/1000, Loss: 1.2940236632074473
Epoch 178/1000, Loss: 1.2858318783011782
Epoch 179/1000, Loss: 1.2777583995619488
Epoch 180/1000, Loss: 1.2698025844692753
Epoch 181/1000, Loss: 1.2619637536403072
Epoch 182/1000, Loss: 1.2542411914014349
Epoch 183/1000, Loss: 1.246634146399767
Epoch 184/1000, Loss: 1.23914183225432
Epoch 185/1000, Loss: 1.231763428245648
Epoch 186/1000, Loss: 1.2244980800434762
Epoch 187/1000, Loss: 1.2173449004714176
Epoch 188/1000, Loss: 1.2103029703081973
Epoch 189/1000, Loss: 1.2033713391247705
Epoch 190/1000, Loss: 1.196549026156659
Epoch 191/1000, Loss: 1.1898350212109288
Epoch 192/1000, Loss: 1.1832282856071057
Epoch 193/1000, Loss: 1.1767277531515294
Epoch 194/1000, Loss: 1.1703323311441995
Epoch 195/1000, Loss: 1.1640409014176019
Epoch 196/1000, Loss: 1.1578523214063354
Epoch 197/1000, Loss: 1.151765425246869
Epoch 198/1000, Loss: 1.1457790249060622
Epoch 199/1000, Loss: 1.1398919113373376
Epoch 200/1000, Loss: 1.1341028556630401
Epoch 201/1000, Loss: 1.1284106103814315
Epoch 202/1000, Loss: 1.1228139105964992
Epoch 203/1000, Loss: 1.1173114752687106
Epoch 204/1000, Loss: 1.1119020084845563
Epoch 205/1000, Loss: 1.106584200742547
Epoch 206/1000, Loss: 1.1013567302532201
Epoch 207/1000, Loss: 1.0962182642504728
Epoch 208/1000, Loss: 1.0911674603114296
Epoch 209/1000, Loss: 1.0862029676818656
Epoch 210/1000, Loss: 1.0813234286041278
Epoch 211/1000, Loss: 1.0765274796443687
Epoch 212/1000, Loss: 1.0718137530158276
Epoch 213/1000, Loss: 1.0671808778948475
Epoch 214/1000, Loss: 1.0626274817262709
Epoch 215/1000, Loss: 1.0581521915148822
Epoch 216/1000, Loss: 1.0537536350995476
Epoch 217/1000, Loss: 1.0494304424067888
Epoch 218/1000, Loss: 1.0451812466805814
Epoch 219/1000, Loss: 1.0410046856853004
Epoch 220/1000, Loss: 1.0368994028788
Epoch 221/1000, Loss: 1.0328640485528486
Epoch 222/1000, Loss: 1.0288972809382335
Epoch 223/1000, Loss: 1.024997767272076
Epoch 224/1000, Loss: 1.0211641848250996
Epoch 225/1000, Loss: 1.0173952218867892
Epoch 226/1000, Loss: 1.0136895787066298
Epoch 227/1000, Loss: 1.0100459683898302
Epoch 228/1000, Loss: 1.006463117746185
Epoch 229/1000, Loss: 1.0029397680909742
Epoch 230/1000, Loss: 0.9994746759970285
Epoch 231/1000, Loss: 0.9960666139973444
Epoch 232/1000, Loss: 0.9927143712378546
Epoch 233/1000, Loss: 0.9894167540802022
Epoch 234/1000, Loss: 0.9861725866545712
Epoch 235/1000, Loss: 0.9829807113628534
Epoch 236/1000, Loss: 0.9798399893326172
Epoch 237/1000, Loss: 0.9767493008225387
Epoch 238/1000, Loss: 0.9737075455801241
Epoch 239/1000, Loss: 0.9707136431527134
Epoch 240/1000, Loss: 0.9677665331529035
Epoch 241/1000, Loss: 0.9648651754796472
Epoch 242/1000, Loss: 0.9620085504964164
Epoch 243/1000, Loss: 0.9591956591678974
Epoch 244/1000, Loss: 0.9564255231567934
Epoch 245/1000, Loss: 0.9536971848823608
Epoch 246/1000, Loss: 0.9510097075423756
Epoch 247/1000, Loss: 0.9483621751002671
Epoch 248/1000, Loss: 0.9457536922391869
Epoch 249/1000, Loss: 0.9431833842848004
Epoch 250/1000, Loss: 0.9406503970986024
Epoch 251/1000, Loss: 0.9381538969435526
Epoch 252/1000, Loss: 0.935693070323816
Epoch 253/1000, Loss: 0.9332671238003815
Epoch 254/1000, Loss: 0.9308752837842997
Epoch 255/1000, Loss: 0.9285167963092471
Epoch 256/1000, Loss: 0.926190926785094
Epoch 257/1000, Loss: 0.9238969597340967
Epoch 258/1000, Loss: 0.9216341985113028
Epoch 259/1000, Loss: 0.919401965010687
Epoch 260/1000, Loss: 0.9171995993584962
Epoch 261/1000, Loss: 0.9150264595952201
Epoch 262/1000, Loss: 0.9128819213475386
Epoch 263/1000, Loss: 0.9107653774915462
Epoch 264/1000, Loss: 0.9086762378084859
Epoch 265/1000, Loss: 0.9066139286341655
Epoch 266/1000, Loss: 0.9045778925031681
Epoch 267/1000, Loss: 0.9025675877889076
Epoch 268/1000, Loss: 0.9005824883405142
Epoch 269/1000, Loss: 0.8986220831174874
Epoch 270/1000, Loss: 0.8966858758229788
Epoch 271/1000, Loss: 0.8947733845365272
Epoch 272/1000, Loss: 0.8928841413469962
Epoch 273/1000, Loss: 0.8910176919864303
Epoch 274/1000, Loss: 0.8891735954654683
Epoch 275/1000, Loss: 0.8873514237109317
Epoch 276/1000, Loss: 0.885550761206131
Epoch 277/1000, Loss: 0.8837712046344052
Epoch 278/1000, Loss: 0.8820123625263577
Epoch 279/1000, Loss: 0.8802738549112109
Epoch 280/1000, Loss: 0.8785553129726618
Epoch 281/1000, Loss: 0.8768563787095872
Epoch 282/1000, Loss: 0.8751767046019027
Epoch 283/1000, Loss: 0.8735159532818557
Epoch 284/1000, Loss: 0.8718737972109939
Epoch 285/1000, Loss: 0.8702499183630251
Epoch 286/1000, Loss: 0.8686440079127508
Epoch 287/1000, Loss: 0.8670557659312381
Epoch 288/1000, Loss: 0.8654849010873629
Epoch 289/1000, Loss: 0.8639311303558349
Epoch 290/1000, Loss: 0.8623941787318006
Epoch 291/1000, Loss: 0.8608737789520919
Epoch 292/1000, Loss: 0.8593696712231768
Epoch 293/1000, Loss: 0.8578816029558461
Epoch 294/1000, Loss: 0.8564093285066621
Epoch 295/1000, Loss: 0.8549526089261709
Epoch 296/1000, Loss: 0.8535112117138794
Epoch 297/1000, Loss: 0.8520849105799724
Epoch 298/1000, Loss: 0.8506734852137476
Epoch 299/1000, Loss: 0.8492767210587268
Epoch 300/1000, Loss: 0.8478944090943987
Epoch 301/1000, Loss: 0.8465263456245364
Epoch 302/1000, Loss: 0.8451723320720277
Epoch 303/1000, Loss: 0.8438321747801516
Epoch 304/1000, Loss: 0.842505684820224
Epoch 305/1000, Loss: 0.841192677805534
Epoch 306/1000, Loss: 0.8398929737114851
Epoch 307/1000, Loss: 0.838606396701855
Epoch 308/1000, Loss: 0.8373327749610805
Epoch 309/1000, Loss: 0.8360719405324707
Epoch 310/1000, Loss: 0.8348237291622527
Epoch 311/1000, Loss: 0.833587980149347
Epoch 312/1000, Loss: 0.8323645362007688
Epoch 313/1000, Loss: 0.8311532432925542
Epoch 314/1000, Loss: 0.8299539505360976
Epoch 315/1000, Loss: 0.8287665100497977
Epoch 316/1000, Loss: 0.8275907768359
Epoch 317/1000, Loss: 0.8264266086624242
Epoch 318/1000, Loss: 0.8252738659500638
Epoch 319/1000, Loss: 0.8241324116639496
Epoch 320/1000, Loss: 0.8230021112101538
Epoch 321/1000, Loss: 0.8218828323368311
Epoch 322/1000, Loss: 0.8207744450398718
Epoch 323/1000, Loss: 0.8196768214729566
Epoch 324/1000, Loss: 0.8185898358618943
Epoch 325/1000, Loss: 0.8175133644231254
Epoch 326/1000, Loss: 0.8164472852862757
Epoch 327/1000, Loss: 0.8153914784206389
Epoch 328/1000, Loss: 0.8143458255654727
Epoch 329/1000, Loss: 0.8133102101639911
Epoch 330/1000, Loss: 0.8122845173009302
Epoch 331/1000, Loss: 0.8112686336435718
Epoch 332/1000, Loss: 0.8102624473861093
Epoch 333/1000, Loss: 0.8092658481972306
Epoch 334/1000, Loss: 0.808278727170806
Epoch 335/1000, Loss: 0.8073009767795618
Epoch 336/1000, Loss: 0.8063324908316206
Epoch 337/1000, Loss: 0.8053731644297938
Epoch 338/1000, Loss: 0.8044228939335107
Epoch 339/1000, Loss: 0.8034815769232674
Epoch 340/1000, Loss: 0.8025491121674826
Epoch 341/1000, Loss: 0.8016253995916501
Epoch 342/1000, Loss: 0.8007103402496696
Epoch 343/1000, Loss: 0.7998038362972547
Epoch 344/1000, Loss: 0.7989057909673037
Epoch 345/1000, Loss: 0.7980161085471275
Epoch 346/1000, Loss: 0.7971346943574323
Epoch 347/1000, Loss: 0.7962614547329533
Epoch 348/1000, Loss: 0.7953962970046357
Epoch 349/1000, Loss: 0.7945391294832727
Epoch 350/1000, Loss: 0.7936898614444963
Epoch 351/1000, Loss: 0.7928484031150332
Epoch 352/1000, Loss: 0.7920146656601347
Epoch 353/1000, Loss: 0.7911885611720919
Epoch 354/1000, Loss: 0.7903700026597524
Epoch 355/1000, Loss: 0.7895589040389568
Epoch 356/1000, Loss: 0.7887551801238165
Epoch 357/1000, Loss: 0.787958746618758
Epoch 358/1000, Loss: 0.7871695201112595
Epoch 359/1000, Loss: 0.7863874180652147
Epoch 360/1000, Loss: 0.7856123588148528
Epoch 361/1000, Loss: 0.7848442615591565
Epoch 362/1000, Loss: 0.7840830463567178
Epoch 363/1000, Loss: 0.783328634120973
Epoch 364/1000, Loss: 0.7825809466157684
Epoch 365/1000, Loss: 0.7818399064512035
Epoch 366/1000, Loss: 0.7811054370797073
Epoch 367/1000, Loss: 0.7803774627923032
Epoch 368/1000, Loss: 0.7796559087150232
Epoch 369/1000, Loss: 0.7789407008054338
Epoch 370/1000, Loss: 0.7782317658492387
Epoch 371/1000, Loss: 0.7775290314569268
Epoch 372/1000, Loss: 0.776832426060438
Epoch 373/1000, Loss: 0.7761418789098181
Epoch 374/1000, Loss: 0.7754573200698412
Epoch 375/1000, Loss: 0.7747786804165778
Epoch 376/1000, Loss: 0.774105891633889
Epoch 377/1000, Loss: 0.7734388862098298
Epoch 378/1000, Loss: 0.7727775974329495
Epoch 379/1000, Loss: 0.772121959388473
Epoch 380/1000, Loss: 0.7714719069543536
Epoch 381/1000, Loss: 0.7708273757971913
Epoch 382/1000, Loss: 0.7701883023680015
Epoch 383/1000, Loss: 0.7695546238978397
Epoch 384/1000, Loss: 0.7689262783932668
Epoch 385/1000, Loss: 0.768303204631658
Epoch 386/1000, Loss: 0.7676853421563545
Epoch 387/1000, Loss: 0.7670726312716524
Epoch 388/1000, Loss: 0.7664650130376329
Epoch 389/1000, Loss: 0.7658624292648364
Epoch 390/1000, Loss: 0.7652648225087784
Epoch 391/1000, Loss: 0.7646721360643135
Epoch 392/1000, Loss: 0.7640843139598508
Epoch 393/1000, Loss: 0.7635013009514243
Epoch 394/1000, Loss: 0.7629230425166231
Epoch 395/1000, Loss: 0.7623494848483873
Epoch 396/1000, Loss: 0.7617805748486761
Epoch 397/1000, Loss: 0.7612162601220114
Epoch 398/1000, Loss: 0.7606564889689081
Epoch 399/1000, Loss: 0.7601012103791921
Epoch 400/1000, Loss: 0.7595503740252164
Epoch 401/1000, Loss: 0.7590039302549821
Epoch 402/1000, Loss: 0.7584618300851708
Epoch 403/1000, Loss: 0.7579240251940925
Epoch 404/1000, Loss: 0.7573904679145635
Epoch 405/1000, Loss: 0.7568611112267138
Epoch 406/1000, Loss: 0.7563359087507336
Epoch 407/1000, Loss: 0.7558148147395685
Epoch 408/1000, Loss: 0.7552977840715671
Epoch 409/1000, Loss: 0.7547847722430888
Epoch 410/1000, Loss: 0.7542757353610786
Epoch 411/1000, Loss: 0.7537706301356147
Epoch 412/1000, Loss: 0.7532694138724372
Epoch 413/1000, Loss: 0.7527720444654612
Epoch 414/1000, Loss: 0.7522784803892818
Epoch 415/1000, Loss: 0.7517886806916784
Epoch 416/1000, Loss: 0.7513026049861192
Epoch 417/1000, Loss: 0.750820213444277
Epoch 418/1000, Loss: 0.750341466788556
Epoch 419/1000, Loss: 0.7498663262846406
Epoch 420/1000, Loss: 0.7493947537340631
Epoch 421/1000, Loss: 0.7489267114668023
Epoch 422/1000, Loss: 0.7484621623339134
Epoch 423/1000, Loss: 0.7480010697001934
Epoch 424/1000, Loss: 0.7475433974368864
Epoch 425/1000, Loss: 0.7470891099144334
Epoch 426/1000, Loss: 0.7466381719952684
Epoch 427/1000, Loss: 0.7461905490266638
Epoch 428/1000, Loss: 0.7457462068336311
Epoch 429/1000, Loss: 0.7453051117118762
Epoch 430/1000, Loss: 0.7448672304208125
Epoch 431/1000, Loss: 0.7444325301766385
Epoch 432/1000, Loss: 0.7440009786454747
Epoch 433/1000, Loss: 0.7435725439365684
Epoch 434/1000, Loss: 0.7431471945955663
Epoch 435/1000, Loss: 0.7427248995978541
Epoch 436/1000, Loss: 0.7423056283419694
Epoch 437/1000, Loss: 0.7418893506430847
Epoch 438/1000, Loss: 0.7414760367265656
Epoch 439/1000, Loss: 0.7410656572216032
Epoch 440/1000, Loss: 0.7406581831549215
Epoch 441/1000, Loss: 0.7402535859445627
Epoch 442/1000, Loss: 0.7398518373937499
Epoch 443/1000, Loss: 0.7394529096848261
Epoch 444/1000, Loss: 0.739056775373275
Epoch 445/1000, Loss: 0.7386634073818179
Epoch 446/1000, Loss: 0.7382727789945931
Epoch 447/1000, Loss: 0.7378848638514115
Epoch 448/1000, Loss: 0.7374996359420963
Epoch 449/1000, Loss: 0.7371170696008991
Epoch 450/1000, Loss: 0.7367371395009984
Epoch 451/1000, Loss: 0.7363598206490771
Epoch 452/1000, Loss: 0.7359850883799798
Epoch 453/1000, Loss: 0.7356129183514503
Epoch 454/1000, Loss: 0.7352432865389481
Epoch 455/1000, Loss: 0.7348761692305432
Epoch 456/1000, Loss: 0.7345115430218917
Epoch 457/1000, Loss: 0.7341493848112871
Epoch 458/1000, Loss: 0.7337896717947906
Epoch 459/1000, Loss: 0.7334323814614384
Epoch 460/1000, Loss: 0.7330774915885261
Epoch 461/1000, Loss: 0.7327249802369683
Epoch 462/1000, Loss: 0.7323748257467338
Epoch 463/1000, Loss: 0.7320270067323554
Epoch 464/1000, Loss: 0.7316815020785147
Epoch 465/1000, Loss: 0.7313382909356981
Epoch 466/1000, Loss: 0.7309973527159277
Epoch 467/1000, Loss: 0.7306586670885615
Epoch 468/1000, Loss: 0.7303222139761668
Epoch 469/1000, Loss: 0.7299879735504617
Epoch 470/1000, Loss: 0.729655926228327
Epoch 471/1000, Loss: 0.7293260526678866
Epoch 472/1000, Loss: 0.7289983337646537
Epoch 473/1000, Loss: 0.7286727506477464
Epoch 474/1000, Loss: 0.7283492846761671
Epoch 475/1000, Loss: 0.7280279174351467
Epoch 476/1000, Loss: 0.7277086307325539
Epoch 477/1000, Loss: 0.7273914065953672
Epoch 478/1000, Loss: 0.7270762272662079
Epoch 479/1000, Loss: 0.7267630751999367
Epoch 480/1000, Loss: 0.7264519330603073
Epoch 481/1000, Loss: 0.7261427837166843
Epoch 482/1000, Loss: 0.725835610240813
Epoch 483/1000, Loss: 0.7255303959036535
Epoch 484/1000, Loss: 0.7252271241722669
Epoch 485/1000, Loss: 0.7249257787067591
Epoch 486/1000, Loss: 0.7246263433572797
Epoch 487/1000, Loss: 0.7243288021610741
Epoch 488/1000, Loss: 0.7240331393395885
Epoch 489/1000, Loss: 0.7237393392956285
Epoch 490/1000, Loss: 0.7234473866105672
Epoch 491/1000, Loss: 0.723157266041606
Epoch 492/1000, Loss: 0.7228689625190825
Epoch 493/1000, Loss: 0.7225824611438283

In [50]:
print(model.weights)
print(model.bias)

tensor([[-0.1260],
        [-0.2689],
        [-0.0729],
        [-0.1736],
        [-0.0121],
        [ 0.0453],
        [-0.1122],
        [ 0.1648],
        [-0.0955],
        [ 0.3119],
        [-0.2116],
        [-0.1302],
        [ 0.0250],
        [ 0.0609],
        [-0.0477],
        [ 0.1916],
        [ 0.1877],
        [ 0.0655],
        [ 0.2039],
        [-0.4204],
        [ 0.0631],
        [ 0.3866],
        [ 0.2639],
        [ 0.4703],
        [-0.0596],
        [-0.2097],
        [-0.1415],
        [-0.3450],
        [-0.1042],
        [ 0.2312]], dtype=torch.float64, requires_grad=True)
tensor([-0.3606], dtype=torch.float64, requires_grad=True)

In [54]:
with torch.no_grad():
    y_test_pred = model.forward(X_test_tensor)
    y_test_pred_labels = (y_test_pred >= 0.5).float()
    accuracy = (y_test_pred_labels.squeeze() == y_test_tensor).float().mean()
    print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")

Test Accuracy: 59.65%